# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QTA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_RSACipher(object):
    def setupUi(self, RSACipher):
        RSACipher.setObjectName("RSACipher")
        RSACipher.resize(1063, 407)
        self.centralwidget = QtWidgets.QWidget(RSACipher)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 70, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 190, 71, 16))
        self.label_5.setObjectName("label_5")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(690, 20, 101, 31))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(140, 310, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(380, 310, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(650, 310, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(880, 310, 93, 28))
        self.btn_verify.setObjectName("btn_verify")
        self.txt_plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plaintext.setGeometry(QtCore.QRect(120, 70, 381, 87))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_ciphertext.setGeometry(QtCore.QRect(120, 190, 381, 87))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(620, 70, 381, 87))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(620, 190, 381, 87))
        self.txt_sign.setObjectName("txt_sign")
        RSACipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RSACipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 26))
        self.menubar.setObjectName("menubar")
        RSACipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RSACipher)
        self.statusbar.setObjectName("statusbar")
        RSACipher.setStatusBar(self.statusbar)

        self.retranslateUi(RSACipher)
        QtCore.QMetaObject.connectSlotsByName(RSACipher)

    def retranslateUi(self, RSACipher):
        _translate = QtCore.QCoreApplication.translate
        RSACipher.setWindowTitle(_translate("RSACipher", "MainWindow"))
        self.label.setText(_translate("RSACipher", "RSA Cipher"))
        self.label_2.setText(_translate("RSACipher", "Plain Text: "))
        self.label_3.setText(_translate("RSACipher", "Cipher Text: "))
        self.label_4.setText(_translate("RSACipher", "Information: "))
        self.label_5.setText(_translate("RSACipher", "Signature: "))
        self.btn_gen_keys.setText(_translate("RSACipher", "Generate Keys"))
        self.btn_encrypt.setText(_translate("RSACipher", "Encrypt"))
        self.btn_decrypt.setText(_translate("RSACipher", "Decrypt"))
        self.btn_sign.setText(_translate("RSACipher", "Sign"))
        self.btn_verify.setText(_translate("RSACipher", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSACipher = QtWidgets.QMainWindow()
    ui = Ui_RSACipher()
    ui.setupUi(RSACipher)
    RSACipher.show()
    sys.exit(app.exec_())
